repos:
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
    - id: codespell
      files: ^.*\.(jl|md|yaml)$
      args: ["--ignore-words=.codespell-ignore-words.txt"]

ci:  # https://pre-commit.ci/
  autofix_prs: false
  autoupdate_schedule: weekly
